{
    "checksum": "19f4cb285dec43ea736f44175362825ef5e98199a7d3c2a5a15e00265a0ce0dd",
    "file": "mpi4py_fix.patch",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-diff"
    },
    "number_of_duplicates": 2,
    "package": "adios",
    "path": "adios/1.13.1-28.2/debian/patches/mpi4py_fix.patch",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/adios/1.13.1-28.2/",
        "metric": {
            "size": 23688
        },
        "pts_link": "https://tracker.debian.org/pkg/adios",
        "sloc": [
            [
                "ansic",
                133236
            ],
            [
                "f90",
                8791
            ],
            [
                "sh",
                7783
            ],
            [
                "python",
                7648
            ],
            [
                "xml",
                3793
            ],
            [
                "makefile",
                2994
            ],
            [
                "cpp",
                2340
            ],
            [
                "java",
                626
            ],
            [
                "sed",
                16
            ],
            [
                "perl",
                8
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org:/science-team/adios.git",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/adios/1.13.1-28.2/debian/patches/mpi4py_fix.patch",
    "stat": {
        "perms": "rw-r--r--",
        "size": 997,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.13.1-28.2"
}